### ISSUE TITLE
Closing alert will scroll to the selected button

### ISSUE THREAD

**Issue by angrykoala** [limonte/sweetalert2#751] opened 2017-11-28 10:21 UTC
Hi
When closing an alert, if the selected button is out of the screen, the scroll will automatically change to show the selected button.
This can be replicated in the examples at GH pages by selecting one example, scrolling, and pressing enter.

This is particularly annoying, as I'm using sweetalert where the "activate" button is in a header with bootstrap "sticky-top" class, so when closing the modal it will always scroll to the top. This last problem is only present at Google Chrome.

I'm using a default sweetalert button:
```
swal({
  titleText: "Test alert",
  text: "This is a test alert"
});
```

Is there a way to fix this(or disable if it is a wanted feature)?

Thanks

**Comment by limonte** [comment] 2017-11-28 17:00
Hello @angrykoala and thank you for reporting this issue. In order for us to better understand it, could you please make a quick jsfiddle with a header with bootstrap "sticky-top" class and swal.

>JSFiddle template: https://jsfiddle.net/ad3quksn/199/

**Comment by angrykoala** [comment] 2017-11-28 21:48
Hi @limonte 
Here is the fiddle:
https://jsfiddle.net/ad3quksn/225/

To reproduce:
1. Open the example in Google Chrome
2. Scroll down until some top elements are not visible
3. Click on "Open Alert"
4. Close the alert
5. Scroll should be on top again, with the element 1 visible.

In firefox this is not happening, so I guess is not a desired feature

Thanks

**Comment by limonte** [comment] 2017-11-29 06:03
Looks like the issue indeed, I'll take a look at it during the weekend.

**Comment by angrykoala** [comment] 2017-11-29 08:30
Thanks, I'll try to check your project as well to see if I find the problem

**Comment by limonte** [comment] 2017-11-29 08:37
The fix is actually coming in couple of minutes :rocket:

**Comment by angrykoala** [comment] 2017-11-29 08:42
Oh, well, fastest weekend of my life
Thanks!

**Comment by limonte** [comment] 2017-11-29 08:54
- fixed in https://github.com/limonte/sweetalert2/commit/eea3b424aa96c8f678621b806aefb7dd60e47c76
- released in https://github.com/limonte/sweetalert2/releases/tag/v7.0.6
- live demo: https://jsfiddle.net/ad3quksn/226/

**Comment by angrykoala** [comment] 2017-11-29 12:04
I confirm this is fixed in my own application, I think this can be closed now

**Closed** 2017-11-29 12:07 UTC

**Comment by raydawg2000** [comment] 2018-09-27 23:34
Hi, I think this issue has sprung up again.  I cannot reproduce this in jsfiddle but I do have a site I can send a link too.  I don't really want to publicly post the site.  Please advise.

To sum up, I am using Bootstrap 4 and have a submit button at the bottom of my form.  When I click on the submit button I scroll to to the top of the page to show any errors.  Once the alert closes though the page scrolls back down the submit button, but i want it to stay at the top.  I have tried putting the submit button on random places on the page and it auto scrolls to where ever the button is.

**Comment by limonte** [comment] 2018-09-28 09:16
@raydawg2000 a new patch release (7.28.3) has been published, it will fix your issue:

https://jsfiddle.net/s8f12xad/1/

```js
swal({
  onAfterClose: () => window.scrollTo(0,0)
})
```

**Comment by raydawg2000** [comment] 2018-09-28 17:19
@limonte  Just want to say thanks for this, it works great!!  Though I would say this solution may not be ideal because the need to scroll can be conditional.  For instance, I don't want to scroll to the top if the user hits the cancel button or closes via some other method but this solution does it.  Now I can add some additional logic to control this scroll inside the `onAfterClose` method but I feel like its easier to handle this inside the `then` method where I have access to the result and make a choice based on that.

Another idea could be if some kind of input parameter could be provided through the `onAfterClose` method such as event state or input result so logic could be created around it.

Maybe there is a technical reason why it has to go there, I don't know.  Either way, there are ways to work around it but it does add some additional complexity that perhaps isn't necessary.

**Comment by raydawg2000** [comment] 2018-09-28 18:31
Thanks for the reply, your solution was what I ended up doing.  It's not a big deal but if there is a way down the road to simplify this it would be great.  Either way, thanks for your help!

**Comment by limonte** [comment] 2018-09-28 18:49
You're very welcome! Thank you for using SweetAlert2!

If anything related to `onAfterClose()` will change, I'll notify you in this thread.

**Comment by apla12** [comment] 2019-07-12 13:43
Hi boys,

even after clicking on the cancel button or ok the modal is reopening from time to time...
How can I not open it?

` const swalWithBootstrapButtons = Swal.mixin({
          customClass: {
            confirmButton: 'btn btn-success',
            cancelButton: 'btn btn-danger'
          },
          buttonsStyling: false,
        })
        swalWithBootstrapButtons.fire({
          title: 'Tempo encerrado!',
          text: "Para solicitar uma nova senha click no botao 'Reenviar senha provisória'",
          type: 'warning',
          width: '500px',
          showCancelButton: true,
          confirmButtonText: 'Reenviar senha provisória',
          cancelButtonText: 'Cancelar',
          reverseButtons: true,
          allowOutsideClick: true,
        }).then((result) => {
          if (result.value) {
            this.mostraTemporizador = true;
          } else if (result.dismiss === Swal.DismissReason.cancel) {
            swalWithBootstrapButtons.fire(
              'Cancelado',
              'Senha não envida!',
              'error'
            )
          }
        })
      }`

**Comment by objectisliper** [comment] 2019-10-09 08:23
Maybe you just add a bool var, to fix this? sometimes i Don't wanna to scroll, after modal close.
