### ISSUE TITLE
Clicking close button throws error

### ISSUE THREAD

**Issue by Spetnik** [limonte/sweetalert2#562] opened 2017-06-30 09:17 UTC
When clicking the "close" button in an alert, an error is thrown in the console: "Uncaught (in promise) close".

Tested on Chrome.

See https://jsfiddle.net/spetnik/j0y914Lo/

Will try to take a look at the code next week if I have time.

**Comment by limonte** [comment] 2017-06-30 10:44
Duplicate of https://github.com/limonte/sweetalert2/issues/221

**Closed by limonte** 2017-06-30 10:44 UTC
