### ISSUE TITLE
Problem closing the modal in Android's default browser

### ISSUE THREAD

**Issue by lucas-jc** [limonte/sweetalert2#673] opened 2017-10-21 13:31 UTC
I'm having trouble closing the modal using the standard android browser.

The test was:
1- Open the site https://limonte.github.io/sweetalert2/ in the Android browser. (I used AVD API 22 / Android 5.1 and another test in Asus Zenfone 2 Android 5.0)
2- Click the "Show success message"
3- Click the "OK" button. The modal does not close. :(

No errors were shown on the console. I already tried to use core-js and it still did not work.

Thank you.

**Comment by limonte** [comment] 2017-10-24 19:34
For some reason, this is related only to `all.min.js` version. I [replaced it](https://github.com/limonte/sweetalert2/commit/2f127d730b2f2870f08afe635f21801bd3311f83) with regular `.js` + `.css` files and everything works fine now. 

@lucas-jc could you please verify that https://limonte.github.io/sweetalert2/ works for your device, thanks in advance!

**Comment by lucas-jc** [comment] 2017-10-27 15:48
Nice @limonte ! All working now. 

Thanks!

**Comment by limonte** [comment] 2017-10-27 15:57
It's working, but let's not close the issue just now :) We need to figure out what is wrong with `all.min.js` and why it doesn't work with Android native browser. My guess - the CSS injecting doesn't have a proper browsers support.

**Comment by limonte** [comment] 2017-10-29 18:56
Gotcha! The issue is happening because of missing `webkit-` and other prefixes. I can't figure out how to add `autoprefixer` before injecting CSS, @samturrell could you please help with adding `autoprefixer`?

**Comment by samturrell** [comment] 2017-10-30 20:04
I'll take a look!

**Comment by limonte** [comment] 2017-10-30 20:08
Thanks @samturrell!

**Closed** 2017-10-30 21:25 UTC
Labels: bug

**Comment by limonte** [comment] 2017-10-30 21:47
Fixed in [v6.11.3](https://github.com/limonte/sweetalert2/releases/tag/v6.11.3), thanks @lucas-jc for reporting!
