### ISSUE TITLE
Alert changes body padding style

### ISSUE THREAD

**Issue by crabbly** [limonte/sweetalert2#678] opened 2017-10-24 21:54 UTC
Currently, the library will add the `padding-right: 15px;` style to the body whenever it's opened. This breaks my page layout. Is there a way to cancel or remove this?

Thanks.

**Comment by bubjavier** [comment] 2017-11-17 12:13
+1

**Comment by Kappyh** [comment] 2017-12-04 19:48
For me sweet alert will add padding: 15px in a page with scrollbar.

**Comment by a1p4ca** [comment] 2017-12-19 13:59
Why swal add padding in body? What's the purpose of behavior?

**Comment by crabbly** [comment] 2017-12-19 16:25
@a1p4ca The author isn't replying, but I believe the purpose of this padding is to prevent content from moving around when the modal removes the scrollbar. However, in MacOS, the scrollbar never gets removed, and the padding in fact damages the layout.
What OS are you using?

I have tested with the latest versions of Chrome, Safari, Firefox and Opera in MacOS and they all have the same behavior.

**Comment by crabbly** [comment] 2017-12-19 18:00
I just tested this in Windows 10, with the latest versions of Edge and Chrome. Same behavior. The padding damages the layout since the scroll bar is still there.

**Comment by limonte** [comment] 2017-12-19 18:22
@crabbly could you please make a jsfiddle with the simple reproduction of the layout which is getting damaged?

>JSFiddle template: https://jsfiddle.net/ad3quksn/249/

**Comment by crabbly** [comment] 2017-12-19 20:33
@limonte Here it is:
https://jsfiddle.net/crabbly/53wc51o2/

When creating the fiddle, I noticed that the issue is a conflict with the CSS framework I'm using. The issue is that swal assumes the scroll bar will be hidden, and that is not happening. 

Based on the other comments here, I believe that this could be a conflict with other frameworks as well. Would make sense for the library to have a way to turn this behavior on and off depending on the project / environment it is being used. 

We could add a parameter, and use it in `sweetalert2.js` line 367. Add it to that conditional.

I could submit a PR if you agree with it.

**Comment by limonte** [comment] 2017-12-19 20:58
Great! Thanks for the research and the explanation @crabbly!

Please go ahead with the PR, I'll be happy to merge it and release new version asap.

**Comment by limonte** [comment] 2017-12-19 21:07
> We could add a parameter,

I can't come up with a good name for the new parameter :/ Any ideas?

**Comment by crabbly** [comment] 2017-12-19 21:46
Great!
About the parameter name, I was going to ask you about that.

That PR looks good though.

**Comment by limonte** [comment] 2017-12-20 06:47
Merged and released v7.1.2

@crabbly Check out the updated jsfiddle with the new version dependency: https://jsfiddle.net/53wc51o2/5/

@bubjavier @Kappyh @a1p4ca please try v7.1.2 and tell if it fixes the issue for your projects

Thanks everyone for reporting!

**Comment by Kappyh** [comment] 2017-12-20 11:53
**Fixed** @limonte , thank you!! :D

**Comment by limonte** [comment] 2017-12-26 18:01
This looks like a CSS framework issue. I have no idea why Bulma forces vertical scrollbar to be shown always https://github.com/jgthms/bulma/blob/master/sass/base/generic.sass#L28 even if the height of the content is less than the height of the browser's viewport.

The workaround to fix this yet-another-one-cool-framework is to add

```css
html {
  overflow-y: auto;
}
```

**Closed by limonte** 2017-12-26 18:01 UTC

**Comment by ldenoue** [comment] 2020-04-05 15:44
My body was using `display:flex`, but showing the Swal.fire was messing up my layout.
I fixed with:
`.swal2-shown {
  display:flex;
  height:100vh;
}`

**Comment by jinbatsu** [comment] 2021-06-30 19:55
Thanks @ldenoue !

Additional for center content:

```
.swal2-shown { display:flex; height:100vh; justify-content: center; }
```

**Comment by odan** [comment] 2021-07-30 14:39
I had the same issue with Bootstrap 5. To fix it you need to change the `swal2-shown` CSS class and you need to disable `scrollbarPadding`.

```css
.swal2-shown {
    overflow: unset !important;
    padding-right: 0px !important;
}
```

```js
Swal.fire({
    scrollbarPadding: false,
    // optional
    heightAuto: false, 
    // ...
})
// ...
```

**Comment by Opty1712** [comment] 2021-08-17 09:58
@odan thanx, but for me was enough just adding ` scrollbarPadding: false,`

**Comment by yesidacosta** [comment] 2022-08-26 04:10
@odan  This was my solution, Thanks!

**Comment by complanboy2** [comment] 2023-07-02 04:52
> I had the same issue with Bootstrap 5. To fix it you need to change the `swal2-shown` CSS class and you need to disable `scrollbarPadding`.
> 
> ```css
> .swal2-shown {
>     overflow: unset !important;
>     padding-right: 0px !important;
> }
> ```
> 
> ```js
> Swal.fire({
>     scrollbarPadding: false,
>     // optional
>     heightAuto: false, 
>     // ...
> })
> // ...
> ```

This worked for me, Odan, thank you.

**Comment by alexx296** [comment] 2023-07-10 11:15
It would be a better way to set by default scrollbarPadding: false and maybe in some situations you need to enable it, right now you have to always type scrollbarPadding: false cause is enabled by default

**Comment by limonte** [comment] 2023-07-10 11:40
> It would be better to set scrollbarPadding: false as default, and in some situations, you may need to set it true. Currently, you always have to type scrollbarPadding: false because it is true by default.

That's be a breaking change for all our user 🤯 

I'd recommend you to use a [mixin](https://sweetalert2.github.io/#mixin):

```js
const MySwal = Swal.mixin({scrollbarPadding: false})

MySwal.fire(...)
```
