### ISSUE TITLE
ignore customClass

### ISSUE THREAD

**Issue by hannesLP** [limonte/sweetalert2#253] opened 2016-08-16 09:45 UTC
after opening and closing an alert with a customClass (eg. 'swal-wide') and open it afterwords with another customClass (eg. 'swal-small') the prevoius class remains and the new alert has the still the class 'swal-wide'

**Comment by birjolaxew** [comment] 2016-08-16 09:47
Could you provide a JSFiddle? [I cannot reproduce it.](https://jsfiddle.net/usoa6ou5/)

**Comment by limonte** [comment] 2016-08-16 09:48
This issue was fixes couple of months ago. It's fixed in latest, update your dependency.

**Closed by limonte** 2016-08-16 09:48 UTC

**Comment by birjolaxew** [comment] 2016-08-16 09:50
(specific version this was fixed in: [v0.4.5](https://github.com/limonte/sweetalert2/releases/tag/v0.4.5))

**Comment by limonte** [comment] 2016-08-16 09:53
@birjolaxew wow. How have you found that release so fast? Are you magician? :)

**Comment by birjolaxew** [comment] 2016-08-16 10:00
@limonte I am omniscient! (well, [the search is](https://github.com/limonte/sweetalert2/issues?utf8=%E2%9C%93&q=is%3Aissue%20customClass))

**Comment by hannesLP** [comment] 2016-08-16 10:14
i've got it: THANKS
