### ISSUE TITLE
Mouse clicks on buttons doesn't work (pointer-events: none)

### ISSUE THREAD

**Issue by victornpb** [limonte/sweetalert2#488] opened 2017-04-04 21:10 UTC
```
.swal2-container:not(.swal2-in) {
    /* pointer-events: none; */
}
```

I removed this is style because I couldn't interact with the alert buttons. Is this a bug or am I using it wrong.

It was fine before when I was 5.2.0, I just updated to 6.5.5 and it broke. 

```
-    "sweetalert2": "^5.2.0",
+    "sweetalert2": "^6.5.5",
```

Sample code

            swal({
                  title: _t('confirmation.delete.delete'),
                  html: _t('confirmation.delete.deleteMessage', {name: self.model.name}),
                  type: 'warning',
                  showCancelButton: true,
                  confirmButtonColor: '#ed5565',
                  confirmButtonText: _t('confirmation.delete.confirm'),
                  cancelButtonText: _t('confirmation.delete.cancel'),
                }).then(function () {     
                     console.log('OK');
                }, function(){
                    log.debug('Delete Canceled');
                }
            );

**Comment by limonte** [comment] 2017-04-06 08:00
Your example works fine: https://jsfiddle.net/ad3quksn/82/

In your case `.swal2-container` is not getting the `.swal2-in` class when a modal is shown, please debug your app or create the jsfiddle where this issue is reproducible.

**Comment by limonte** [comment] 2017-04-08 11:03
I'm closing this issue due to incativity. Leave the comment if needed and I will reopen it

**Closed by limonte** 2017-04-08 11:03 UTC
Labels: feedback required

**Comment by portonhealthdevback** [comment] 2019-05-03 14:31
`.swal2-container:not(.swal2-in) {
    pointer-events: none;
}`

so apparently disabling this css line fixes the problem. This is the package code by the author. so will post something as soon as i find the final solution
