### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by akibderaiya** [limonte/sweetalert2#528] opened 2017-05-16 09:16 UTC
i am developing one react redux application. In this application i have use this sweetalert2 module but when i call 

` swal('Oops...', 'Something went wrong!', 'error');
`
then i got error like ReferenceError: document is not defined and alert is not desplay

**Comment by limonte** [comment] 2017-05-16 09:18
Duplicate of https://github.com/limonte/sweetalert2/issues/454

**Closed by limonte** 2017-05-16 09:18 UTC
