### ISSUE TITLE
Selected for radio or select

### ISSUE THREAD

**Issue by thelastinuit** [limonte/sweetalert2#222] opened 2016-07-21 14:22 UTC
Is there anyway to set a selected radio or select input?

If not, could it be a new feat?

**Comment by samturrell** [comment] 2016-07-21 14:24
The `inputValue` option can be used to set the initial value, or are you talking in terms of setting it afterwards via an API?

**Comment by limonte** [comment] 2016-07-21 14:29
Duplicate of https://github.com/limonte/sweetalert2/issues/207

**Closed** 2016-07-21 14:29 UTC

**Comment by thelastinuit** [comment] 2016-07-21 15:56
@samturrell inputValue works for input select/radio type?
