### ISSUE TITLE
Uncaught (in promise) overlay

### ISSUE THREAD

**Issue by federicolucca** [limonte/sweetalert2#185] opened 2016-06-22 09:43 UTC
Hi,

i found this error, "Uncaught (in promise) overlay" this happen when i click out of the modal

https://jsfiddle.net/28tu8f7p/

Thanks
Federico

**Comment by limonte** [comment] 2016-06-22 09:45
duplicate of https://github.com/limonte/sweetalert2/issues/177

**Closed by limonte** 2016-06-22 09:45 UTC

**Comment by limonte** [comment] 2016-06-27 21:49
starting from v4.0.6 you can fix this issue this way: https://jsfiddle.net/limon/2ya7akjq/

**Comment by limonte** [comment] 2016-08-07 23:07
### https://github.com/limonte/sweetalert2#handling-dismissals

**Comment by carlHandy** [comment] 2019-01-29 22:34
@limonte the solution you provided does not work. 

`.done()` is not a function. Is there another way to resolve this?
