### ISSUE TITLE
Feature Request: Growl functionality

### ISSUE THREAD

**Issue by simon1tan** [limonte/sweetalert2#663] opened 2017-10-12 19:44 UTC
Wouldn't it would be nice to have a built-in growl functionality? I know there are dozens of plugins out there already but I like sweetalert2 and I rather not have to add another plugin but I will if I have to. It seems like sweetalert2 has all the components necessary to do it, it just needs to be implemented. The other plugins are strictly for growl and have no input funtionality which is sad. Not feature creep, I don't think. Thanks for listening.

**Comment by limonte** [comment] 2017-10-12 20:23
what do you mean by "growl"?

**Comment by simon1tan** [comment] 2017-10-12 20:32
Growl is basically a popup message without being modal. The point is to let the user know an event has occurred without needing the user to click on anything and without being intrusive. The popup usually appears top right corner but can appear anywhere via options. By default, the popup also disappears after a certain time. See http://codeseven.github.io/toastr/ or https://sciactive.com/pnotify/#demos-simple. Sweetalert2 has all the components to do this already and I think with a few additions, could be made to work.

**Comment by toverux** [comment] 2017-10-14 12:29
It's indeed out of scope of the current library but I've already thought about that. I often find myself using SweetAlert2 and Toastr (http://codeseven.github.io/toastr/) at the same time.

SweetAlerts are good for important informations, important decisions (confirmation popups with confirm/cancel, etc), that is, everything that should be blocking / that the user should not miss.
But they are invasive in other situations (ex: "Your work has been correclty saved", "_some long operation_ has finished!", etc).

The problem is that SweetAlert and Toastr (and other libraries that fill the same needs) don't have the same style or APIs at all. That leads to wobbly UX/UI unless you take much time to customize both (colours, animations, paddings...).

The original goal of SweetAlert was to provide a replacement for JavaScript's alerts. But I don't think that much people would hate to have the possibility to get lightweight and simple _toasts_ as it's a very good, modern alternative to alerts, which are sometimes heavy and overkill.

It's an important design decision. What do you think about this @limonte? I'd understand that you prefer to focus on the alerts paradigm. But as an user, I'd be happy to have only one library to handle those types of interactions with the user. Plus, that's quite of a killer feature. I've never seen a lib that does the two at the same time, although this is very common to mix the two paradigms in a real-life app.

Another alternative: maybe this could be a sister library of SweetAlert and they may share a common base and/or design?

**Comment by limonte** [comment] 2017-10-15 08:19
Less is more. Modal dialogs and notifications look pretty similar at the first sight, but in fact, those are quite different. 

For example, the accessibility is totally different for modal window and notification. The size and complexity of the repo will grow twice if we implement both functionalities in one place.

> The problem is that SweetAlert and Toastr (and other libraries that fill the same needs) don't have the same style or APIs at all. That leads to wobbly UX/UI unless you take much time to customize both (colours, animations, paddings...).

I'm planning to put some time into the proper customization of the plugin, so adjusting colors/paddings/animations won't be so painful in future.

> Another alternative: maybe this could be a sister library of SweetAlert and they may share a common base and/or design? SweetToast2 ^_^

Currently, I'm in the really tough schedule and won't be able to dedicate a proper amount of time for that.

**Comment by toverux** [comment] 2017-10-16 16:34
Yeah, you have good points, and I must specify that I expressed myself as a very regular user, not as the responsible contributor :smile:

Just a little reaction (I don't expect such a feature to be implemented right now anyway):

> The size and complexity of the repo will grow twice

Pretty sure you're pessimistic! I think that, given some refactors and intelligent use of the existing codebase, we can make great reuses of code: positioning and DOM "engine", style and look and feel, animations, the famous SweetAlert icons, etc. I can't express myself on a11y though, sadly, I don't know enough in that area (aria?) for now.
But I think the visual/UX result could be pretty neat!

**Comment by limonte** [comment] 2017-10-18 20:53
Are we getting closer to deliver this feature: https://limonte.github.io/sweetalert2/#position ? :)

**Comment by toverux** [comment] 2017-10-18 22:12
Don't tempt me! :smile: 

```css
.swal2-toast {
    padding: 15px !important;
    font-size: 60%;
}

.swal2-toast .swal2-title, .swal2-toast .swal2-content {
    text-align: left;
}

.swal2-toast .swal2-icon {
    float: left;
    margin: 0 20px 0 0;
}

.swal2-toast .swal2-buttonswrapper {
    text-align: right;
}
```

```js
swal({
    //=> toastify
    position: 'top-right',
    overlay: false,
    customClass: 'swal2-toast',
    width: '450px',

    //=> basics
    type: 'success',
    title: 'Done!',
    text: 'Your work has been saved!',
    useRejections: false
});
```

![image](https://user-images.githubusercontent.com/1343250/31745192-fe34eab0-b461-11e7-9038-fc67657ca0bc.png)

**Comment by limonte** [comment] 2017-10-19 08:52
> The size and complexity of the repo will grow twice

@acupajoe proved that I was wrong :)

**Comment by limonte** [comment] 2017-10-19 09:17
@toverux @acupajoe do you guys already have accounts on [patreon.com](https://patreon.com)? If not, please create, it would be honor to me to be your first supporter :)

**Comment by limonte** [comment] 2017-11-01 16:41
Good news, @simon1tan and anyone else interested in this feature :tada: 

It was merged today and available for testing! If you want to check how it will work in the next major:

1. clone the repo: `git clone https://github.com/limonte/sweetalert2.git`
2. build: `gulp` 
3. test:

```js
swal({
  ...
  toast: true
})
```

**Comment by limonte** [comment] 2017-11-16 08:07
Released! :tada: 

https://github.com/limonte/sweetalert2/releases/tag/v7.0.0

:warning: Pay attention to breaking changes from the new major release!

**Closed by limonte** 2017-11-16 08:07 UTC
Labels: enhancement, next major
