### ISSUE TITLE
Alert is bigger than the screen on smaller screens

### ISSUE THREAD

**Issue by blairjo** [limonte/sweetalert2#479] opened 2017-03-31 08:27 UTC
Hi,

On a smaller screen, such as an Iphone4, an alert that has quite a lot of content does not fit the screen - it overflows in both directions. Using the Chrome emulator it seems fine - it pretty much fits the screen - but not on a real device. 

You can recreate this on the demo page, using the "A message with a custom image and CSS animation disabled" example.
See attached screenshot.

Thanks

John

![realdeviceoverflow](https://cloud.githubusercontent.com/assets/19793829/24542601/2bde60d4-15f4-11e7-90d2-a7ce55d194e6.PNG)

**Comment by blairjo** [comment] 2017-03-31 10:27
Update: 
The old Iphone I had for testing was on an old version of IOS (8.2)
I updated to the latest IOS and it seems fine now.

I guess it depends how far back you want to support :)

Cheers

**Comment by limonte** [comment] 2017-03-31 10:34
Thanks for the update, because I wasn't able to reproduce :)

SweetAlert2 doesn't support iOS 8.x, so I'm closing this issue.

Thanks for reporting and have a nice day!

**Closed by limonte** 2017-03-31 10:34 UTC
Labels: bug
