### ISSUE TITLE
Sweetalert not working in UC Browser (Android)

### ISSUE THREAD

**Issue by cooberr** [limonte/sweetalert2#513] opened 2017-04-23 08:47 UTC
In UC Browser blank window is shown instead of sweetalert2 popup.

**Comment by cooberr** [comment] 2017-04-23 10:22
UC Browser mobile*

**Comment by limonte** [comment] 2017-04-23 18:12
Thanks for reporting this issue @cooberr !

I will add the UC Browser support. It has a huge market share in countries like India, China, Indonesia and I personally care about those users.  

Currently I can confirm that everything works fine both in iOS UC Browser and Windows UC Browser. These days I will find an Android device and test in it.

Meanwhile, could you please specify the device and Android version you're using?

**Comment by cooberr** [comment] 2017-04-23 18:34
ASUS Zenfone 2, Android 5, also tried on samsung.

If it will help you - I added https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js in head and popup has appeared, but its width is incorrect (also only in UC Browser on Android)

![image](https://cloud.githubusercontent.com/assets/27913553/25316261/56f36cb2-286c-11e7-8ada-18be408b4374.png)

**Comment by cooberr** [comment] 2017-04-23 18:39
One more thing - first version of sweetalert doesn`t have this problem.

**Comment by limonte** [comment] 2017-04-23 19:44
Allright, the main issue is fixed by adding a polyfill for ES6 Promises. I added the note about that to docs, thanks for the useful feedback!

About the second issue with the modal width - could you please try our demos (https://limonte.github.io/sweetalert2/) with the same device (ASUS Zenfone 2, Android 5) and tell if there's the same issue with all other examples or it's the issue specific to your project.

Thanks!

**Comment by cooberr** [comment] 2017-04-23 19:51
yes, absolutely the same situation with incorrect width as on screenshot above:

![image](https://cloud.githubusercontent.com/assets/27913553/25316896/5ca5da90-2877-11e7-8f90-c79979002bfc.png)

**Comment by limonte** [comment] 2017-04-23 19:56
Looks like an issue for me. Since it's different from the original one, I separated it to https://github.com/limonte/sweetalert2/issues/514

Once again, thanks for help!

**Closed by limonte** 2017-04-23 19:56 UTC

**Comment by iCankat** [comment] 2017-12-01 16:39
sweetalert not work some mobile phones (exp: samsung galaxy s3) what is the problem? Most phones do not work on some phones while I am working without problems. Butona does not react when touched. It's a strange problem.

**Comment by limonte** [comment] 2017-12-01 16:51
> Most phones do not work on some phones while I am working without problems.

![](https://i.imgur.com/euPGYyS.png)

**Comment by iCankat** [comment] 2017-12-01 18:11
Hahah sorry for my bad English bro. In summery, some phones have no problem. But there are problems with some phones. Android phone Galaxy S3 does not do anything when the button is touched on the devices. How to fix this problem?
