### ISSUE TITLE
Customizing elements of preset templates

### ISSUE THREAD

**Issue by KHam0425** [limonte/sweetalert2#154] opened 2016-06-01 23:20 UTC
In some cases, it may be desired to reduce the size of the icons for "warning", "error", "info" etc, as well as the font sizes and line spacing for the title and padding between elements.  Is there an easy way to add a flag that would use "percentages" or "em" so that the content of the alert can be scaled to fit the height and width settings?

If someone sets their height and width, but then those values are overwritten when the contents of the alert are too large for the modal's space.  The same goes for a scroll bar being added to the modal, which changes a design concept, when it could be possible to scale the modal elements to fit a pre-determined size.

Maybe I'll see if I can do something with this if I can find some free time this weekend.

**Comment by limonte** [comment] 2016-06-01 23:36
possible duplicate of https://github.com/limonte/sweetalert2/issues/25

jsfiddle with scaled modal: https://jsfiddle.net/1drfdqg7/

**Comment by KHam0425** [comment] 2016-06-01 23:47
Not quite a duplicate, as he's setting the font-size with media queries.  Is it possible to add properties to swal to include baseFontSize: 20 and scaleSwal: true instead of adding the custom class?  

At least with that approach, you can find a comfortable starting point for the look you prefer, and then if developers want to increase the size, they can change the baseFontSize to a value that fits their design goals.  Then, we can set the transforms for each media query he makes instead of the hard-coded values that he suggested in #25.

**Comment by limonte** [comment] 2016-06-02 00:08
The only way, as far as I know, to scale the whole modal with icons is `transform: scale()`, but if you have a better idea, I'd like to see your PR :)

**Comment by KHam0425** [comment] 2016-06-02 00:09
Working on it, trying to merge his idea with mine.

**Comment by samturrell** [comment] 2016-06-02 08:00
Personally, i'd like to see all styling specific options removed from the plugin, as it's much more efficient and flexible to style using css and media queries to get the desired effect.

**Comment by KHam0425** [comment] 2016-06-02 08:04
I used vh and vw for the text elements and was able to get a good scaling
solution working tonight. It's ugly, but works. With a bit of jquery, I
could control transform scaling with dynamic values if I spent some more
time on it. I'm not sure if it's worth it for my personal use.

**Comment by limonte** [comment] 2016-06-02 09:12
>  With a bit of jquery

:)

I totally agree with @samturrell - all additional styling should be outside the plugin.

**Closed by limonte** 2016-06-02 09:12 UTC
