### ISSUE TITLE
Cannot read property 'querySelectorAll' when a spacebar key is pressed

### ISSUE THREAD

**Issue by caiodearaujo** [limonte/sweetalert2#557] opened 2017-06-28 11:32 UTC
Displays console error if the spacebar key is pressed when 'Sweetalert2' is not displayed.

`ERROR TypeError: Cannot read property 'querySelectorAll' of null
    at getFocusableElements (sweetalert2.js:250)
    at handleKeyDown (sweetalert2.js:1074)
    at wrapFn (zone.js:1032)
    at wrapFn (zone.js:1032)
    at wrapFn (zone.js:1032)
    at wrapFn (zone.js:1032)
    at wrapFn (zone.js:1032)
    at wrapFn (zone.js:1032)
    at ZoneDelegate.webpackJsonp.622.ZoneDelegate.invokeTask (zone.js:414)
    at Object.onInvokeTask (core.es5.js:4140)`

I'm using Angular2

**Comment by limonte** [comment] 2017-06-28 12:05
Duplicate of https://github.com/limonte/sweetalert2/issues/523, upgrade swal2 to the latest.

**Closed by limonte** 2017-06-28 12:05 UTC
