### ISSUE TITLE
PopUp losing center orientation on mobile devices

### ISSUE THREAD

**Issue by quma** [limonte/sweetalert2#189] opened 2016-06-26 11:19 UTC
Hallo,

Test your examples on mobile phones (in my case iPhone 6): 
- A message with custom icon and css animation disabled.
- A message with custom width, padding and background. 

If you open PopUp on standard orientation and than change to landscape orientation the PopUp is no longer centered on screen after that.

I also test it with Google Chrome Developer tools with the same result.
Sometimes it looks correctly but in the most cases its not centered in Y direction.
Best regards

**Comment by limonte** [comment] 2016-06-27 16:41
can anyone confirm this issue? I can't reproduce it on Android smartphone and on iPad.

**Comment by quma** [comment] 2016-06-27 17:40
I can also confirm on iPad 3 works correctly

**Comment by quma** [comment] 2016-06-27 17:44
But you can test it with Google Developer Tools, select iPhone 6, iPhone 6 Plus or Nexus 6P you can correctly reproduce the bug. The Dev Tools iPad shows it also correctly.

**Comment by limonte** [comment] 2016-06-27 17:52
yeah, I can see it now. Thank you @quma, I'll try to fix this.

**Comment by limonte** [comment] 2016-07-04 19:32
Fixed in [v4.0.8](https://github.com/limonte/sweetalert2/releases/tag/v4.0.8)

**Closed by limonte** 2016-07-04 19:32 UTC
