### ISSUE TITLE
When plugging from npm, do I need to import styles separately?

### ISSUE THREAD

**Issue by mityukov** [limonte/sweetalert2#490] opened 2017-04-05 09:50 UTC
I'm not sure if it's my theme or if I'm simply plugging the SA wrong…

Here's my 'bootstrap' code:
```javascript
window.swal = require('sweetalert2');
```

Here's the command I enter in browser's Development Tools:
```javascript
swal("Oops...", "Something went wrong!", "error");
```

Here's what I get in the result (it's bottom-left of the viewport):
![Screenshot](https://www.evernote.com/l/ACiu3cSC-3BG7oM877NJNwa6gSX78_bW-xwB/image.png)

Do I miss anything? Should I import CSS styles separately, for instance?

P.S.: this is the theme I'm using: https://colorlib.com/polygon/gentelella/index.html

**Comment by mityukov** [comment] 2017-04-05 10:02
UPDATE: just plugged it in via CDN. All looks great. So, it's me plugging the SA wrongly. Could you provide a working "plug via npm" example, where it has styles?

**Comment by limonte** [comment] 2017-04-05 10:11
Duplicate of https://github.com/limonte/sweetalert2/issues/422

**Closed by limonte** 2017-04-05 10:11 UTC

**Comment by toverux** [comment] 2017-04-05 19:01
Oh, I should really update those docs...
